AgroInventario/AgroInventario/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Modulos.distAvicola.urls')),
    path('', include('Modulos.distAvicola.urls2')),
    path('accounts/',include('django.contrib.auth.urls'))
]

AgroInventario/Modulos/distAvicola/urls.py
from django.urls import path 
from .views import *
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('',index, name='index'),
    path('salir/', salir, name='salir' ),
    path('huevos/',huevos, name='huevos'),
    path('contabilidad/',contabilidad, name='contabilidad'),
    path('cuidado/',cuidado, name='cuidado'),
    path('recurso/',recurso, name='recurso'),
    path('recursos/gasto/<int:id_recurso>',agregarGasto, name='gasto'),
    path('recursos/adicion', adicion, name='adicion'),
    path('recursos/editarRecurso/<int:id>', editarRecurso, name='editar_recurso'),
    path('eliminarRecurso/<int:id>', eliminarRecurso,name='eliminarRecurso'),
    path('recursos/',recursos, name='recursos'),
    path('cuidado/',cuidado, name='cuidado')
]

AgroInventario/Modulos/distAvicola/models.py
from django.db import models

class Tamaño(models.Model):
    id = models.AutoField(primary_key=True) 
    nombre = models.CharField(max_length=45)

class Producto(models.Model):
    id = models.AutoField(primary_key=True)  
    cantidad = models.IntegerField()
    costo_produccion = models.FloatField()
    tamaño = models.OneToOneField(Tamaño, on_delete=models.SET_NULL, null=True)

class Lote(models.Model):
    id = models.AutoField(primary_key=True)
    produc = models.ForeignKey(Producto,to_field="id",  on_delete=models.CASCADE, null=True)
    cantidad = models.IntegerField(default=0)
    fecha_creacion = models.DateField()
    fecha_vencimiento =  models.DateField(null=True)
    costo_produccion = models.FloatField()
    precio_individual = models.FloatField()

class ventas(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=45)
    cantidad = models.IntegerField()
    precio_final = models.FloatField()
    fecha = models.DateField()

class DetalleVentas(models.Model):
    venta = models.ForeignKey(ventas, to_field="id" , on_delete=models.SET_NULL, null=True)
    lotes = models.ManyToManyField(Lote)
    
class recursos(models.Model):
    id = models.AutoField(primary_key=True) 
    nombre_recurso = models.CharField(max_length=45)
    descripcion = models.TextField()
    cantidad_disponible = models.IntegerField()

class gastos_recursos(models.Model):
    id = models.AutoField(primary_key=True)
    id_recurso = models.ForeignKey(recursos, to_field='id', on_delete=models.SET_NULL, null=True)
    precio = models.FloatField()
    fecha = models.DateField()
    cantidad_agregada = models.IntegerField()

class salud_gallinas(models.Model):
    id = models.AutoField(primary_key=True)
    tipo_accion = models.CharField(max_length=45)
    fecha = models.DateField()
    id_recurso = models.ForeignKey(recursos, to_field='id', on_delete=models.SET_NULL, null=True)
    comentarios = models.TextField()
    cantidad_recurso_usado = models.IntegerField()


    

AgroInventario/Modulos/distAvicola/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .models import recursos, gastos_recursos ,salud_gallinas
from .formularios import RecursoForm , GastoForm, SaludForm
from .models import *
from django.db.models import Count

@login_required
@csrf_protect
def salir(request):
    logout(request)
    return redirect('/')

@csrf_protect
@login_required
def index(request):
    return render(request, 'index.html')

@csrf_protect
@login_required
def huevos(request):
    pro = Producto.objects.all()
    return render(request, 'adm-huevos.html', {'Producto':pro})

def venta(request):
    ventas_unicas = ventas.objects.all()
    return render(request, 'adm-ventas.html', {'ventas': ventas_unicas})

@csrf_protect
@login_required
def recurso(request):
    recursos_list = recursos.objects.all()
    return render(request, 'adm-recursos.html',{'recursos_list': recursos_list})

@csrf_protect
@login_required
def contabilidad(request):
    return render(request, 'adm-contabilidad.html')

@csrf_protect
@login_required
def agregarGasto(request, id_recurso):
    recurso = recursos.objects.get(id=id_recurso)
    if request.method == 'POST':
        formulario = GastoForm(request.POST)
        if formulario.is_valid():
            gasto = formulario.save(commit=False)
            gasto.id_recurso = recurso
            gasto.save()
            recurso.cantidad_disponible += gasto.cantidad_agregada
            recurso.save()
            messages.success(request, '¡Gasto Agregado con Exito!')   
            return redirect('recurso')
    else:
        formulario = GastoForm()
    return render(request, 'adm-agregarGasto.html', {'formulario': formulario , 'recurso' : recurso} )

@csrf_protect
@login_required
def adicion(request):
    formulario = RecursoForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        messages.success(request, '¡Recurso Agregado con Exito!')   
        return redirect('recurso')
    return render(request, 'adm-adicion.html', {'formulario': formulario})



@csrf_protect
@login_required
def editarRecurso(request, id):
    recurso = recursos.objects.get(id=id)
    formulario = RecursoForm(request.POST or None, request.FILES or None, instance=recurso)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('recurso')
    return render(request, 'adm-editarRecurso.html', {'formulario': formulario , 'recurso' : recurso})



@csrf_protect
@login_required
def eliminarRecurso(request, id):
    recurso_delete = get_object_or_404(recursos, id=id)
    recurso_delete.delete(using=None, keep_parents=False)
    messages.error(request,"¡Recurso Eliminado!")
    return redirect('recurso')



@csrf_protect
@login_required
def cuidado(request):
    salud_list = salud_gallinas.objects.all()
    recursos_disponibles = recursos.objects.all()
    if request.method == 'POST':
        formulario = SaludForm(request.POST)
        if formulario.is_valid():
            tipo_accion = formulario.cleaned_data['tipo_accion']
            fecha = formulario.cleaned_data['fecha']
            comentarios = formulario.cleaned_data['comentarios']
            cantidad_recurso_usado = formulario.cleaned_data['cantidad_recurso_usado']
            id_recurso_id = request.POST['id_recurso'] 
            
            recurso = get_object_or_404(recursos, pk=id_recurso_id)
            
            if cantidad_recurso_usado > recurso.cantidad_disponible:
                messages.error(request, 'No hay suficiente cantidad disponible de este recurso.')
                return redirect('cuidado')
            
            cuidado_gallinas = salud_gallinas.objects.create(
                tipo_accion=tipo_accion,
                fecha=fecha,
                comentarios=comentarios,
                cantidad_recurso_usado=cantidad_recurso_usado,
                id_recurso_id=id_recurso_id 
            )
            
            recurso.cantidad_disponible -= cantidad_recurso_usado
            recurso.save()

            messages.success(request, 'Se registro el cuidado con exito.')
            return redirect('cuidado') 
            
    else:
        formulario = SaludForm()

    return render(request, 'adm-cuidado.html', {'formulario': formulario, 'recursos_disponibles': recursos_disponibles, 'salud_list': salud_list})

AgroInventario/Modulos/distAvicola/templates/add_tamano.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Agregar tamaño</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
            <center>
                {% if error_message %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ error_message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
            </center>
            {% if Tamaño %}
            <form method="post" action="/add_tamano/">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_dep" class="form-label">Tamaño</label>
                    <select class="form-select" id="tamaño" name="tamaño" required>
                        <option value="">Seleccione un tamaño</option>
                        {% for tam in Tamaño %}
                        <option value="{{ tam.id }}">Huevo {{ tam.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="precio" class="form-label">Precio</label>
                    <input type="text" class="form-control" id="precio" name="precio" required>
                </div>
                <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Agregar</button>
            </form>
            {% endif %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

AgroInventario/Modulos/distAvicola/templates/add_ventas.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Guardar venta</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'add_venta' %}">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_dep" class="form-label">Producto</label>
            <select class="form-select" id="producto" name="producto">
              <option value="">Seleccione un Producto</option>
              {% for pro in Producto %}
              <option value="{{ pro.id }}">Huevo {{ pro.tamaño.nombre }}, Cantidad disponible: {{pro.cantidad}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label for="nombre" class="form-label">Nombre cliente:</label>
            <input type="text" class="form-control" id="nombre" name="nombre" min="0" required>
          </div>
          <div class="mb-3">
            <label for="precio" class="form-label">Cantidad a vender:</label>
            <input type="number" class="form-control" id="cantidad" name="cantidad" min="1" required>
          </div>
          <div class="mb-3">
            <label for="fecha" class="form-label">Fecha de venta:</label>
            <input type="date" class="form-control" id="fecha" name="fecha" required>
          </div>
          <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Agregar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>

AgroInventario/Modulos/distAvicola/templates/adm-adicion.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Agregar Recurso</title>
    <link rel="icon" type="image/png" href="{% static 'multimedia/granja.jpg' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>

    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editar_recurso">Crear Recurso</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'adicion' %}" method="POST">
        <div class="modal-body">
        {% include 'form-adicion.html'%}
      </div>
    </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  </body>
</html>

AgroInventario/Modulos/distAvicola/templates/adm-agregarGasto.html
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editar_recurso">Agregar Gasto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% if recurso %}
            <form enctype="multipart/form-data" method="post" action="{% url 'gasto' recurso.id %}">
                {% csrf_token %}
                <input type="hidden" id="id_recurso" name="id_recurso" value="{{ recurso.id }}">
                <div class="modal-body">
                    <div class="form-group mt-4 mb-4">
                        <label for="precio">Precio:</label>
                        <input type="number" class="form-control form-control-lg" id="precio" name="precio" min="0" step="0.01" required>
                    </div>
                    <div class="form-group mt-4 mb-4">
                        <label for="fecha">Fecha:</label>
                        <input type="date" class="form-control form-control-lg" id="fecha" name="fecha" required>
                    </div>
                    <div class="form-group mt-4 mb-4">
                        <label for="cantidad_agregada">Cantidad Agregada:</label>
                        <input type="number" class="form-control form-control-lg" id="cantidad_agregada" name="cantidad_agregada" min="0" required>
                    </div>
                    <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Registrar</button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </form>
            {% endif %}
        </div>
    </div>

AgroInventario/Modulos/distAvicola/templates/adm-cuidado.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cuidado Gallinas</title>
    <link rel="icon" type="image/png" href="{% static 'multimedia/granja.jpg' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar" style="background-color: #72c55d;">
      <div class="container">
        <a class="navbar-brand text-light">AgroInventario</a>
        <form class="d-flex" role="search">
          <a id="cerrar" href="{% url 'index' %}" class="me-3 btn btn-warning">Regresar</a>
          <a id="cerrar" href="{% url 'salir' %}" class="btn btn-danger text-light">Cerrar Sesión</a>
        </form>
      </div>
    </nav>
    <div class="container p-5">
      <div>
        {% if messages %}
          {% for message in messages %}
            {% if message.tags == 'success' %}
              <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong class="text-dark">{{ message }}</strong>
              </div>
            {% elif message.tags == 'error' %}
              <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong class="text-dark">{{ message }}</strong>
              </div>
            {% endif %}
          {% endfor %}
          {% endif %}
      </div>


    <h1 class="text-center mt-3">Listado de Cuidados</h1>
    <a  data-bs-toggle="modal" data-bs-target="#ModalSalud" type="submit" class="btn btn-success mt-3 mb-3"><i class="fas fa-plus"></i> Agregar cuidado</a>
    <table class="table text-center">
    <thead>
    <tr>
      <th scope="col">Tipo de Accion</th>
      <th scope="col">Fecha</th>
      <th scope="col">Recurso</th>
      <th scope="col">Cantidad Utilizada</th>
      <th scope="col">Comentarios</th>
    </tr>
  </thead>
  <tbody>
    {% for salud in salud_list %}
    <tr>
      <td>{{ salud.tipo_accion}}</td>
      <td>{{  salud.fecha|date:"d/m/Y" }}</td>
      <td>{{ salud.id_recurso.nombre_recurso }}</td>
      <td>{{ salud.cantidad_recurso_usado}}</td>
      <td>{{ salud.comentarios }}</td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
  </div>  
  <div class="modal fade" id="ModalSalud" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Registrar Cuidado</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group mt-4 mb-4">
                <label for="accion">Tipo de Acción:</label>
                <input type="text" class="form-control" id="accion" name="tipo_accion" required>
            </div>
            <div class="form-group mt-4 mb-4">
                <label for="id_fecha">Fecha:</label>
                <input type="date" class="form-control" id="id_fecha" name="fecha" required>
            </div>
            <div class="form-group mt-4 mb-4">
              <label for="id_recurso">Seleccione recurso utilizado:</label>
              <select class="form-control" id="id_recurso" name="id_recurso" required>
                <option value="">Seleccione un recurso</option>
                  {% for recurso in recursos_disponibles %}
                      <option value="{{ recurso.id }}">{{ recurso.nombre_recurso }}, Cantidad disponible: {{recurso.cantidad_disponible}}</option>
                  {% endfor %}
              </select>
          </div>
            <div class="form-group mt-4 mb-4">
                <label for="id_cantidad_recurso_usado">Cantidad de recurso usado:</label>
                <input type="number" class="form-control" id="id_cantidad_recurso_usado" name="cantidad_recurso_usado" min="1" required>
            </div>
            <div class="form-group mt-4 mb-4">
              <label for="comentarios">Comentario:</label>
              <textarea class="form-control" id="comentarios" name="comentarios" rows="3" required></textarea>
          </div>      
            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Agregar acción</button>
        </form>	
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    <script>
      setTimeout(function() {
        $('.alert').alert('close');
      }, 5000);
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  </body>
</html>

AgroInventario/Modulos/distAvicola/templates/adm-editarRecurso.html
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editar_recurso">Editar Recurso</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        {% if recurso %}
        <form  method="POST" action="{% url 'editar_recurso' recurso.id %}">
        <div class="modal-body">
          <input type="hidden" id="id_recurso" name="id_recurso" value="{{ recurso.id }}">
        {% include 'form-adicion.html'%}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </form>
      {% endif %}
      </div>
    </div>
  </div>

AgroInventario/Modulos/distAvicola/templates/adm-ventas.html
{% load static %}
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ventas</title>
  <link rel="icon" type="image/png" href="{% static 'multimedia/granja.jpg' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar" style="background-color: #72c55d;">
    <div class="container">
      <a class="navbar-brand text-white">AgroInventario</a>
      <form class="d-flex" role="search">
        <a id="cerrar" href="{% url 'index' %}" class="me-3 btn btn-warning">Regresar</a>
        <a id="cerrar" href="{% url 'salir' %}" class="btn btn-danger text-white">Cerrar Sesión</a>
      </form>
    </div>
  </nav>
  <br>
  <div class="container">
    <center>
      {% if error_message %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ error_message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
    </center>
    <center>
      {% if message %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
    </center>
    <h1 class="text-center mt-3">Listado de Ventas</h1>
    <a class="btn btn-success" onclick="abrir_modal_add_venta('{% url 'pag_add_venta' %}')"><i class="fas fa-plus"></i>
      Agregar venta</a>
    <table class="table text-center">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Tipo de huevo vendido</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Ganancias</th>
          <th scope="col">Fecha</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for venta in ventas %}
        <tr>
          <td>{{ venta.nombre }}</td>
          {% with lote=venta.detalleventas_set.first.lotes.first %}
          <td>Huevo {{ lote.produc.tamaño.nombre }}</td>
          {% endwith %}
          <td>{{ venta.cantidad }}</td>
          <td>{{ venta.precio_final }}</td>
          <td>{{ venta.fecha }}</td>
          <td>
            <a onclick="abrir_modal_r_cambio('{% url 'r_devolucion' venta.id %}')" class="btn btn-primary"><i
                class="fa-solid fa-rotate-right"></i>
              Realizar cambio</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="modal fade" id="add_venta" role="dialog">
    </div>
    <div class="modal fade" id="realizar_cambio" role="dialog">
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
</body>

</html>

AgroInventario/Modulos/distAvicola/templates/devolucion.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Realizar cambio</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% if ventas %}
            <form method="post" action="{% url 'r_devolucion' ventas.id %}">
                {% csrf_token %}
                {% with lote=ventas.detalleventas_set.first.lotes.first %}
                <div class="mb-3">
                    <label for="producto" class="form-label">Producto:</label>
                    <select class="form-select" id="producto" name="producto">
                        <option value="{{ lote.produc.id }}" selected>Huevo {{ lote.produc.tamaño.nombre }}, Cantidad disponible: {{ lote.produc.cantidad }}</option>
                    </select>
                </div>
                {% endwith %}
                <div class="mb-3">
                    <label for="cantidad" class="form-label">Cantidad a devolver:</label>
                    <input type="number" class="form-control" id="cantidad" name="cantidad" min="0" required>
                </div>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-rotate-right"></i> Realizar cambio</button>
            </form>
            {% endif %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>